name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-11
      volumes:
        - my_docker_volume:/volume_mount
        - /data/my_data
      options: --cpus 1
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.4
        
    - name: Build with Maven
      run: mvn clean install --file pom.xml
